name: Message issue

on:
  issues:
    types: [opened]

jobs:
  greet-author:
    runs-on: ubuntu-latest

    steps:
      - name: Envoyer un message personnalisé à l'auteur d'une déclaration d'issue
        env:
          AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "Bonjour $AUTHOR, nous avons bien pris en compte votre problème du nom de : $ISSUE_TITLE"
